/**
 * Lingo Lab default vocabulary seed — starter content for every supported
 * language so the Vocabulary / Pronunciation / Listening labs work out of the
 * box in production, even before/without runtime AI generation.
 *
 * Row shape (matches the lingo_vocabulary INSERT):
 *   [target_language, category, word, translation, ipa, example_sentence,
 *    example_translation, difficulty]
 *
 * Categories: greetings, numbers, colors, food, family.
 * Example sentences are provided for the European languages; for ja/hi the
 * pronunciation field carries a romanization and examples are enriched by AI.
 */

const SEED_VOCAB = [
  // ---------------------------------------------------------------- Spanish (es)
  ['es', 'greetings', 'Hola', 'Hello', 'ˈola', '¡Hola! ¿Cómo estás?', 'Hello! How are you?', 1],
  ['es', 'greetings', 'Buenos días', 'Good morning', 'ˈbwenos ˈdi.as', 'Buenos días, señora.', 'Good morning, madam.', 1],
  ['es', 'greetings', 'Gracias', 'Thank you', 'ˈɡɾa.sjas', 'Muchas gracias por tu ayuda.', 'Thank you very much for your help.', 1],
  ['es', 'greetings', 'Adiós', 'Goodbye', 'aˈðjos', 'Adiós, hasta mañana.', 'Goodbye, see you tomorrow.', 1],
  ['es', 'greetings', 'Por favor', 'Please', 'poɾ faˈβoɾ', 'Un café, por favor.', 'A coffee, please.', 1],
  ['es', 'numbers', 'Uno', 'One', 'ˈuno', 'Tengo uno.', 'I have one.', 1],
  ['es', 'numbers', 'Dos', 'Two', 'dos', 'Quiero dos, por favor.', 'I want two, please.', 1],
  ['es', 'numbers', 'Tres', 'Three', 'tɾes', 'Son las tres.', "It's three o'clock.", 1],
  ['es', 'numbers', 'Cuatro', 'Four', 'ˈkwatɾo', 'Hay cuatro sillas.', 'There are four chairs.', 1],
  ['es', 'numbers', 'Cinco', 'Five', 'ˈsiŋko', 'Cinco minutos más.', 'Five more minutes.', 1],
  ['es', 'colors', 'Rojo', 'Red', 'ˈroxo', 'El coche es rojo.', 'The car is red.', 1],
  ['es', 'colors', 'Azul', 'Blue', 'aˈsul', 'El cielo es azul.', 'The sky is blue.', 1],
  ['es', 'colors', 'Verde', 'Green', 'ˈbeɾðe', 'La hierba es verde.', 'The grass is green.', 1],
  ['es', 'colors', 'Amarillo', 'Yellow', 'amaˈɾiʎo', 'El sol es amarillo.', 'The sun is yellow.', 2],
  ['es', 'colors', 'Negro', 'Black', 'ˈneɣɾo', 'El gato es negro.', 'The cat is black.', 1],
  ['es', 'food', 'Agua', 'Water', 'ˈaɣwa', 'Quiero un vaso de agua.', 'I want a glass of water.', 1],
  ['es', 'food', 'Pan', 'Bread', 'pan', 'El pan está fresco.', 'The bread is fresh.', 1],
  ['es', 'food', 'Manzana', 'Apple', 'manˈsana', 'Como una manzana.', 'I eat an apple.', 1],
  ['es', 'food', 'Café', 'Coffee', 'kaˈfe', 'Me gusta el café.', 'I like coffee.', 1],
  ['es', 'food', 'Leche', 'Milk', 'ˈletʃe', 'La leche está fría.', 'The milk is cold.', 1],
  ['es', 'family', 'Madre', 'Mother', 'ˈmaðɾe', 'Mi madre es doctora.', 'My mother is a doctor.', 1],
  ['es', 'family', 'Padre', 'Father', 'ˈpaðɾe', 'Mi padre trabaja aquí.', 'My father works here.', 1],
  ['es', 'family', 'Hermano', 'Brother', 'eɾˈmano', 'Tengo un hermano.', 'I have a brother.', 1],
  ['es', 'family', 'Hija', 'Daughter', 'ˈixa', 'Su hija tiene cinco años.', 'His daughter is five years old.', 2],
  ['es', 'family', 'Amigo', 'Friend', 'aˈmiɣo', 'Él es mi amigo.', 'He is my friend.', 1],

  // ---------------------------------------------------------------- French (fr)
  ['fr', 'greetings', 'Bonjour', 'Hello / Good morning', 'bon-zhoor', 'Bonjour, comment ça va ?', 'Hello, how are you?', 1],
  ['fr', 'greetings', 'Salut', 'Hi', 'sa-lu', 'Salut, ça va ?', 'Hi, how are you?', 1],
  ['fr', 'greetings', 'Merci', 'Thank you', 'mair-see', 'Merci beaucoup !', 'Thank you very much!', 1],
  ['fr', 'greetings', 'Au revoir', 'Goodbye', 'oh ruh-vwar', 'Au revoir, à demain.', 'Goodbye, see you tomorrow.', 1],
  ['fr', 'greetings', "S'il vous plaît", 'Please', 'seel voo pleh', 'Un café, s’il vous plaît.', 'A coffee, please.', 2],
  ['fr', 'numbers', 'Un', 'One', 'uhn', "J'ai un frère.", 'I have one brother.', 1],
  ['fr', 'numbers', 'Deux', 'Two', 'duh', 'Deux cafés, please.', 'Two coffees, please.', 1],
  ['fr', 'numbers', 'Trois', 'Three', 'twah', 'Il est trois heures.', "It's three o'clock.", 1],
  ['fr', 'numbers', 'Quatre', 'Four', 'katr', 'Quatre chaises.', 'Four chairs.', 1],
  ['fr', 'numbers', 'Cinq', 'Five', 'sank', 'Cinq minutes.', 'Five minutes.', 1],
  ['fr', 'colors', 'Rouge', 'Red', 'roozh', 'La voiture est rouge.', 'The car is red.', 1],
  ['fr', 'colors', 'Bleu', 'Blue', 'bluh', 'Le ciel est bleu.', 'The sky is blue.', 1],
  ['fr', 'colors', 'Vert', 'Green', 'vair', "L'herbe est verte.", 'The grass is green.', 1],
  ['fr', 'colors', 'Jaune', 'Yellow', 'zhohn', 'Le soleil est jaune.', 'The sun is yellow.', 1],
  ['fr', 'colors', 'Noir', 'Black', 'nwahr', 'Le chat est noir.', 'The cat is black.', 1],
  ['fr', 'food', 'Eau', 'Water', 'oh', "Je veux de l'eau.", 'I want some water.', 1],
  ['fr', 'food', 'Pain', 'Bread', 'pan', 'Le pain est frais.', 'The bread is fresh.', 1],
  ['fr', 'food', 'Pomme', 'Apple', 'pom', 'Je mange une pomme.', 'I eat an apple.', 1],
  ['fr', 'food', 'Café', 'Coffee', 'ka-fay', "J'aime le café.", 'I like coffee.', 1],
  ['fr', 'food', 'Lait', 'Milk', 'leh', 'Le lait est froid.', 'The milk is cold.', 1],
  ['fr', 'family', 'Mère', 'Mother', 'mair', 'Ma mère est médecin.', 'My mother is a doctor.', 1],
  ['fr', 'family', 'Père', 'Father', 'pair', 'Mon père travaille ici.', 'My father works here.', 1],
  ['fr', 'family', 'Frère', 'Brother', 'frair', "J'ai un frère.", 'I have a brother.', 1],
  ['fr', 'family', 'Sœur', 'Sister', 'sur', "J'ai une sœur.", 'I have a sister.', 1],
  ['fr', 'family', 'Ami', 'Friend', 'a-mee', "C'est mon ami.", 'He is my friend.', 1],

  // ---------------------------------------------------------------- German (de)
  ['de', 'greetings', 'Hallo', 'Hello', 'HA-lo', 'Hallo, wie geht es dir?', 'Hello, how are you?', 1],
  ['de', 'greetings', 'Guten Morgen', 'Good morning', 'GOO-ten MOR-gen', 'Guten Morgen!', 'Good morning!', 1],
  ['de', 'greetings', 'Danke', 'Thank you', 'DAN-kuh', 'Danke schön!', 'Thank you very much!', 1],
  ['de', 'greetings', 'Auf Wiedersehen', 'Goodbye', 'owf VEE-der-zayn', 'Auf Wiedersehen!', 'Goodbye!', 2],
  ['de', 'greetings', 'Bitte', 'Please', 'BIT-tuh', 'Einen Kaffee, bitte.', 'A coffee, please.', 1],
  ['de', 'numbers', 'Eins', 'One', 'ayns', 'Ich habe eins.', 'I have one.', 1],
  ['de', 'numbers', 'Zwei', 'Two', 'tsvay', 'Zwei Kaffee, bitte.', 'Two coffees, please.', 1],
  ['de', 'numbers', 'Drei', 'Three', 'dry', 'Es ist drei Uhr.', "It's three o'clock.", 1],
  ['de', 'numbers', 'Vier', 'Four', 'feer', 'Vier Stühle.', 'Four chairs.', 1],
  ['de', 'numbers', 'Fünf', 'Five', 'fuenf', 'Fünf Minuten.', 'Five minutes.', 1],
  ['de', 'colors', 'Rot', 'Red', 'roht', 'Das Auto ist rot.', 'The car is red.', 1],
  ['de', 'colors', 'Blau', 'Blue', 'blow', 'Der Himmel ist blau.', 'The sky is blue.', 1],
  ['de', 'colors', 'Grün', 'Green', 'gruen', 'Das Gras ist grün.', 'The grass is green.', 1],
  ['de', 'colors', 'Gelb', 'Yellow', 'gelp', 'Die Sonne ist gelb.', 'The sun is yellow.', 1],
  ['de', 'colors', 'Schwarz', 'Black', 'shvarts', 'Die Katze ist schwarz.', 'The cat is black.', 1],
  ['de', 'food', 'Wasser', 'Water', 'VAS-ser', 'Ich möchte Wasser.', 'I want water.', 1],
  ['de', 'food', 'Brot', 'Bread', 'broht', 'Das Brot ist frisch.', 'The bread is fresh.', 1],
  ['de', 'food', 'Apfel', 'Apple', 'AP-fel', 'Ich esse einen Apfel.', 'I eat an apple.', 1],
  ['de', 'food', 'Kaffee', 'Coffee', 'KA-fay', 'Ich mag Kaffee.', 'I like coffee.', 1],
  ['de', 'food', 'Milch', 'Milk', 'milkh', 'Die Milch ist kalt.', 'The milk is cold.', 1],
  ['de', 'family', 'Mutter', 'Mother', 'MOO-ter', 'Meine Mutter ist Ärztin.', 'My mother is a doctor.', 1],
  ['de', 'family', 'Vater', 'Father', 'FAH-ter', 'Mein Vater arbeitet hier.', 'My father works here.', 1],
  ['de', 'family', 'Bruder', 'Brother', 'BROO-der', 'Ich habe einen Bruder.', 'I have a brother.', 1],
  ['de', 'family', 'Schwester', 'Sister', 'SHVES-ter', 'Ich habe eine Schwester.', 'I have a sister.', 1],
  ['de', 'family', 'Freund', 'Friend', 'froynt', 'Er ist mein Freund.', 'He is my friend.', 1],

  // ---------------------------------------------------------------- Italian (it)
  ['it', 'greetings', 'Ciao', 'Hello / Bye', 'chow', 'Ciao, come stai?', 'Hi, how are you?', 1],
  ['it', 'greetings', 'Buongiorno', 'Good morning', 'bwon-JOR-no', 'Buongiorno!', 'Good morning!', 1],
  ['it', 'greetings', 'Grazie', 'Thank you', 'GRAH-tsyeh', 'Grazie mille!', 'Thank you very much!', 1],
  ['it', 'greetings', 'Arrivederci', 'Goodbye', 'ar-ree-veh-DER-chee', 'Arrivederci!', 'Goodbye!', 2],
  ['it', 'greetings', 'Per favore', 'Please', 'per fa-VOH-reh', 'Un caffè, per favore.', 'A coffee, please.', 1],
  ['it', 'numbers', 'Uno', 'One', 'OO-no', 'Ho uno.', 'I have one.', 1],
  ['it', 'numbers', 'Due', 'Two', 'DOO-eh', 'Due caffè, per favore.', 'Two coffees, please.', 1],
  ['it', 'numbers', 'Tre', 'Three', 'treh', 'Sono le tre.', "It's three o'clock.", 1],
  ['it', 'numbers', 'Quattro', 'Four', 'KWAT-tro', 'Quattro sedie.', 'Four chairs.', 1],
  ['it', 'numbers', 'Cinque', 'Five', 'CHEEN-kweh', 'Cinque minuti.', 'Five minutes.', 1],
  ['it', 'colors', 'Rosso', 'Red', 'ROS-so', "L'auto è rossa.", 'The car is red.', 1],
  ['it', 'colors', 'Blu', 'Blue', 'bloo', 'Il cielo è blu.', 'The sky is blue.', 1],
  ['it', 'colors', 'Verde', 'Green', 'VER-deh', "L'erba è verde.", 'The grass is green.', 1],
  ['it', 'colors', 'Giallo', 'Yellow', 'JAL-lo', 'Il sole è giallo.', 'The sun is yellow.', 1],
  ['it', 'colors', 'Nero', 'Black', 'NEH-ro', 'Il gatto è nero.', 'The cat is black.', 1],
  ['it', 'food', 'Acqua', 'Water', 'AH-kwa', 'Voglio dell’acqua.', 'I want some water.', 1],
  ['it', 'food', 'Pane', 'Bread', 'PAH-neh', 'Il pane è fresco.', 'The bread is fresh.', 1],
  ['it', 'food', 'Mela', 'Apple', 'MEH-la', 'Mangio una mela.', 'I eat an apple.', 1],
  ['it', 'food', 'Caffè', 'Coffee', 'kaf-FEH', 'Mi piace il caffè.', 'I like coffee.', 1],
  ['it', 'food', 'Latte', 'Milk', 'LAT-teh', 'Il latte è freddo.', 'The milk is cold.', 1],
  ['it', 'family', 'Madre', 'Mother', 'MAH-dreh', 'Mia madre è medico.', 'My mother is a doctor.', 1],
  ['it', 'family', 'Padre', 'Father', 'PAH-dreh', 'Mio padre lavora qui.', 'My father works here.', 1],
  ['it', 'family', 'Fratello', 'Brother', 'fra-TEL-lo', 'Ho un fratello.', 'I have a brother.', 1],
  ['it', 'family', 'Sorella', 'Sister', 'so-REL-la', 'Ho una sorella.', 'I have a sister.', 1],
  ['it', 'family', 'Amico', 'Friend', 'a-MEE-ko', 'È il mio amico.', 'He is my friend.', 1],

  // ---------------------------------------------------------------- Portuguese (pt)
  ['pt', 'greetings', 'Olá', 'Hello', 'oh-LAH', 'Olá, tudo bem?', 'Hello, how are you?', 1],
  ['pt', 'greetings', 'Bom dia', 'Good morning', 'bom DEE-a', 'Bom dia!', 'Good morning!', 1],
  ['pt', 'greetings', 'Obrigado', 'Thank you', 'oh-bree-GAH-doo', 'Muito obrigado!', 'Thank you very much!', 1],
  ['pt', 'greetings', 'Adeus', 'Goodbye', 'a-DEUSH', 'Adeus, até amanhã.', 'Goodbye, see you tomorrow.', 1],
  ['pt', 'greetings', 'Por favor', 'Please', 'poor fa-VOR', 'Um café, por favor.', 'A coffee, please.', 1],
  ['pt', 'numbers', 'Um', 'One', 'oom', 'Tenho um.', 'I have one.', 1],
  ['pt', 'numbers', 'Dois', 'Two', 'doysh', 'Dois cafés, por favor.', 'Two coffees, please.', 1],
  ['pt', 'numbers', 'Três', 'Three', 'trehsh', 'São três horas.', "It's three o'clock.", 1],
  ['pt', 'numbers', 'Quatro', 'Four', 'KWAH-troo', 'Quatro cadeiras.', 'Four chairs.', 1],
  ['pt', 'numbers', 'Cinco', 'Five', 'SEEN-koo', 'Cinco minutos.', 'Five minutes.', 1],
  ['pt', 'colors', 'Vermelho', 'Red', 'ver-MEH-lyoo', 'O carro é vermelho.', 'The car is red.', 2],
  ['pt', 'colors', 'Azul', 'Blue', 'a-ZOOL', 'O céu é azul.', 'The sky is blue.', 1],
  ['pt', 'colors', 'Verde', 'Green', 'VER-dee', 'A relva é verde.', 'The grass is green.', 1],
  ['pt', 'colors', 'Amarelo', 'Yellow', 'a-ma-REH-loo', 'O sol é amarelo.', 'The sun is yellow.', 1],
  ['pt', 'colors', 'Preto', 'Black', 'PREH-too', 'O gato é preto.', 'The cat is black.', 1],
  ['pt', 'food', 'Água', 'Water', 'AH-gwa', 'Quero água.', 'I want water.', 1],
  ['pt', 'food', 'Pão', 'Bread', 'powng', 'O pão está fresco.', 'The bread is fresh.', 1],
  ['pt', 'food', 'Maçã', 'Apple', 'ma-SAN', 'Como uma maçã.', 'I eat an apple.', 1],
  ['pt', 'food', 'Café', 'Coffee', 'ka-FEH', 'Gosto de café.', 'I like coffee.', 1],
  ['pt', 'food', 'Leite', 'Milk', 'LAY-tee', 'O leite está frio.', 'The milk is cold.', 1],
  ['pt', 'family', 'Mãe', 'Mother', 'mang', 'A minha mãe é médica.', 'My mother is a doctor.', 1],
  ['pt', 'family', 'Pai', 'Father', 'py', 'O meu pai trabalha aqui.', 'My father works here.', 1],
  ['pt', 'family', 'Irmão', 'Brother', 'eer-MOWNG', 'Tenho um irmão.', 'I have a brother.', 1],
  ['pt', 'family', 'Irmã', 'Sister', 'eer-MAN', 'Tenho uma irmã.', 'I have a sister.', 1],
  ['pt', 'family', 'Amigo', 'Friend', 'a-MEE-goo', 'Ele é o meu amigo.', 'He is my friend.', 1],

  // ---------------------------------------------------------------- Japanese (ja)
  ['ja', 'greetings', 'こんにちは', 'Hello', 'konnichiwa', null, null, 1],
  ['ja', 'greetings', 'おはよう', 'Good morning', 'ohayō', null, null, 1],
  ['ja', 'greetings', 'ありがとう', 'Thank you', 'arigatō', null, null, 1],
  ['ja', 'greetings', 'さようなら', 'Goodbye', 'sayōnara', null, null, 2],
  ['ja', 'greetings', 'お願いします', 'Please', 'onegaishimasu', null, null, 2],
  ['ja', 'numbers', '一', 'One', 'ichi', null, null, 1],
  ['ja', 'numbers', '二', 'Two', 'ni', null, null, 1],
  ['ja', 'numbers', '三', 'Three', 'san', null, null, 1],
  ['ja', 'numbers', '四', 'Four', 'yon', null, null, 1],
  ['ja', 'numbers', '五', 'Five', 'go', null, null, 1],
  ['ja', 'colors', '赤', 'Red', 'aka', null, null, 1],
  ['ja', 'colors', '青', 'Blue', 'ao', null, null, 1],
  ['ja', 'colors', '緑', 'Green', 'midori', null, null, 1],
  ['ja', 'colors', '黄色', 'Yellow', 'kiiro', null, null, 2],
  ['ja', 'colors', '黒', 'Black', 'kuro', null, null, 1],
  ['ja', 'food', '水', 'Water', 'mizu', null, null, 1],
  ['ja', 'food', 'パン', 'Bread', 'pan', null, null, 1],
  ['ja', 'food', 'りんご', 'Apple', 'ringo', null, null, 1],
  ['ja', 'food', 'コーヒー', 'Coffee', 'kōhī', null, null, 1],
  ['ja', 'food', '牛乳', 'Milk', 'gyūnyū', null, null, 2],
  ['ja', 'family', '母', 'Mother', 'haha', null, null, 1],
  ['ja', 'family', '父', 'Father', 'chichi', null, null, 1],
  ['ja', 'family', '兄', 'Older brother', 'ani', null, null, 1],
  ['ja', 'family', '姉', 'Older sister', 'ane', null, null, 1],
  ['ja', 'family', '友達', 'Friend', 'tomodachi', null, null, 2],

  // ---------------------------------------------------------------- Hindi (hi)
  ['hi', 'greetings', 'नमस्ते', 'Hello', 'namaste', null, null, 1],
  ['hi', 'greetings', 'सुप्रभात', 'Good morning', 'suprabhāt', null, null, 2],
  ['hi', 'greetings', 'धन्यवाद', 'Thank you', 'dhanyavād', null, null, 1],
  ['hi', 'greetings', 'अलविदा', 'Goodbye', 'alvidā', null, null, 1],
  ['hi', 'greetings', 'कृपया', 'Please', 'kṛpayā', null, null, 1],
  ['hi', 'numbers', 'एक', 'One', 'ek', null, null, 1],
  ['hi', 'numbers', 'दो', 'Two', 'do', null, null, 1],
  ['hi', 'numbers', 'तीन', 'Three', 'tīn', null, null, 1],
  ['hi', 'numbers', 'चार', 'Four', 'chār', null, null, 1],
  ['hi', 'numbers', 'पाँच', 'Five', 'pāñch', null, null, 1],
  ['hi', 'colors', 'लाल', 'Red', 'lāl', null, null, 1],
  ['hi', 'colors', 'नीला', 'Blue', 'nīlā', null, null, 1],
  ['hi', 'colors', 'हरा', 'Green', 'harā', null, null, 1],
  ['hi', 'colors', 'पीला', 'Yellow', 'pīlā', null, null, 1],
  ['hi', 'colors', 'काला', 'Black', 'kālā', null, null, 1],
  ['hi', 'food', 'पानी', 'Water', 'pānī', null, null, 1],
  ['hi', 'food', 'रोटी', 'Bread', 'roṭī', null, null, 1],
  ['hi', 'food', 'सेब', 'Apple', 'seb', null, null, 1],
  ['hi', 'food', 'कॉफ़ी', 'Coffee', 'kŏfī', null, null, 1],
  ['hi', 'food', 'दूध', 'Milk', 'dūdh', null, null, 1],
  ['hi', 'family', 'माँ', 'Mother', 'mā̃', null, null, 1],
  ['hi', 'family', 'पिता', 'Father', 'pitā', null, null, 1],
  ['hi', 'family', 'भाई', 'Brother', 'bhāī', null, null, 1],
  ['hi', 'family', 'बहन', 'Sister', 'bahan', null, null, 1],
  ['hi', 'family', 'दोस्त', 'Friend', 'dost', null, null, 1],

  // ---------------------------------------------------------------- English (en)
  ['en', 'greetings', 'Hello', 'A greeting', 'huh-LOH', 'Hello! How are you?', 'A friendly greeting.', 1],
  ['en', 'greetings', 'Good morning', 'Morning greeting', 'good MOR-ning', 'Good morning, everyone.', 'Said in the morning.', 1],
  ['en', 'greetings', 'Thank you', 'Expressing thanks', 'THANK yoo', 'Thank you for your help.', 'Expressing gratitude.', 1],
  ['en', 'greetings', 'Goodbye', 'A farewell', 'good-BYE', 'Goodbye, see you tomorrow.', 'Said when leaving.', 1],
  ['en', 'greetings', 'Please', 'Polite request', 'pleez', 'A coffee, please.', 'Used for polite requests.', 1],
  ['en', 'numbers', 'One', 'The number 1', 'wun', 'I have one.', 'The number 1.', 1],
  ['en', 'numbers', 'Two', 'The number 2', 'too', 'I want two.', 'The number 2.', 1],
  ['en', 'numbers', 'Three', 'The number 3', 'three', "It's three o'clock.", 'The number 3.', 1],
  ['en', 'numbers', 'Four', 'The number 4', 'for', 'There are four chairs.', 'The number 4.', 1],
  ['en', 'numbers', 'Five', 'The number 5', 'five', 'Five more minutes.', 'The number 5.', 1],
  ['en', 'colors', 'Red', 'A color', 'red', 'The car is red.', 'The color red.', 1],
  ['en', 'colors', 'Blue', 'A color', 'bloo', 'The sky is blue.', 'The color blue.', 1],
  ['en', 'colors', 'Green', 'A color', 'green', 'The grass is green.', 'The color green.', 1],
  ['en', 'colors', 'Yellow', 'A color', 'YEL-oh', 'The sun is yellow.', 'The color yellow.', 1],
  ['en', 'colors', 'Black', 'A color', 'blak', 'The cat is black.', 'The color black.', 1],
  ['en', 'food', 'Water', 'A drink', 'WAH-ter', 'I want a glass of water.', 'Clear drinking liquid.', 1],
  ['en', 'food', 'Bread', 'A food', 'bred', 'The bread is fresh.', 'A baked food.', 1],
  ['en', 'food', 'Apple', 'A fruit', 'A-pul', 'I eat an apple.', 'A round fruit.', 1],
  ['en', 'food', 'Coffee', 'A drink', 'KAW-fee', 'I like coffee.', 'A hot drink.', 1],
  ['en', 'food', 'Milk', 'A drink', 'milk', 'The milk is cold.', 'A white drink.', 1],
  ['en', 'family', 'Mother', 'A parent', 'MUH-ther', 'My mother is a doctor.', 'A female parent.', 1],
  ['en', 'family', 'Father', 'A parent', 'FAH-ther', 'My father works here.', 'A male parent.', 1],
  ['en', 'family', 'Brother', 'A sibling', 'BRUH-ther', 'I have a brother.', 'A male sibling.', 1],
  ['en', 'family', 'Sister', 'A sibling', 'SIS-ter', 'I have a sister.', 'A female sibling.', 1],
  ['en', 'family', 'Friend', 'A companion', 'frend', 'He is my friend.', 'A person you like.', 1],
];

module.exports = SEED_VOCAB;
