const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');

/**
 * Report Generator Utility
 * Handles PDF, Excel, and CSV generation with MultipliersKraft branding
 */

// MultipliersKraft Brand Colors
const BRAND_COLORS = {
  primary: '#f97316',      // Orange
  secondary: '#1e293b',    // Dark slate
  accent: '#10b981',       // Green
  text: '#334155',         // Slate gray
  lightBg: '#f8fafc',      // Light background
  white: '#ffffff',
  headerBg: '#1e293b',     // Dark header
};

// Ensure reports directory exists
const REPORTS_DIR = path.join(__dirname, '../../uploads/reports');
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

/**
 * Generate a unique filename for the report
 */
const generateFileName = (reportType, format) => {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  return `${reportType}_${timestamp}.${format}`;
};

/**
 * Convert hex color to RGB array for PDFKit
 */
const hexToRgb = (hex) => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [
    parseInt(result[1], 16),
    parseInt(result[2], 16),
    parseInt(result[3], 16)
  ] : [0, 0, 0];
};

/**
 * Generate PDF Report with MultipliersKraft branding
 */
const generatePDF = async (reportType, title, data, options = {}) => {
  return new Promise((resolve, reject) => {
    try {
      const fileName = generateFileName(reportType, 'pdf');
      const filePath = path.join(REPORTS_DIR, fileName);

      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        bufferPages: true
      });

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // Header with branding
      addPDFHeader(doc, title, options);

      // Report metadata
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor(BRAND_COLORS.text);
      doc.text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
      if (options.dateRange) {
        doc.text(`Date Range: ${options.dateRange.from} to ${options.dateRange.to}`, { align: 'right' });
      }
      if (options.department && options.department !== 'all') {
        doc.text(`Department: ${options.department}`, { align: 'right' });
      }
      doc.moveDown(1);

      // Add content based on report type
      switch (reportType) {
        case 'user':
          addUserReportContent(doc, data);
          break;
        case 'course-completion':
          addCourseCompletionContent(doc, data);
          break;
        case 'learning-engagement':
          addLearningEngagementContent(doc, data);
          break;
        case 'skills-assessment':
          addSkillsAssessmentContent(doc, data);
          break;
        default:
          addGenericTableContent(doc, data);
      }

      // Footer on each page
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        addPDFFooter(doc, i + 1, pageCount);
      }

      doc.end();

      stream.on('finish', () => {
        resolve({
          fileName,
          filePath,
          format: 'pdf',
          size: fs.statSync(filePath).size
        });
      });

      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
};

/**
 * Add PDF Header with MultipliersKraft branding
 */
const addPDFHeader = (doc, title, options = {}) => {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // Header background
  doc.rect(0, 0, doc.page.width, 80)
     .fill(BRAND_COLORS.headerBg);

  // Brand name
  doc.fontSize(24)
     .fillColor(BRAND_COLORS.primary)
     .text('MultipliersKraft', 50, 25, { continued: false });

  // Tagline
  doc.fontSize(10)
     .fillColor(BRAND_COLORS.white)
     .text('Learning Management System', 50, 52);

  // Report title
  doc.moveDown(2);
  doc.fontSize(20)
     .fillColor(BRAND_COLORS.secondary)
     .text(title, 50, 100, { align: 'center' });

  // Divider line
  doc.moveDown(0.5);
  doc.strokeColor(BRAND_COLORS.primary)
     .lineWidth(2)
     .moveTo(50, doc.y)
     .lineTo(doc.page.width - 50, doc.y)
     .stroke();

  doc.moveDown(1);
};

/**
 * Add PDF Footer
 */
const addPDFFooter = (doc, currentPage, totalPages) => {
  const bottom = doc.page.height - 30;

  // Footer line
  doc.strokeColor(BRAND_COLORS.primary)
     .lineWidth(1)
     .moveTo(50, bottom - 15)
     .lineTo(doc.page.width - 50, bottom - 15)
     .stroke();

  // Footer text
  doc.fontSize(8)
     .fillColor(BRAND_COLORS.text)
     .text(
       'Generated by MultipliersKraft LMS | Confidential',
       50,
       bottom - 10,
       { align: 'left', width: doc.page.width - 200 }
     );

  doc.text(
    `Page ${currentPage} of ${totalPages}`,
    doc.page.width - 100,
    bottom - 10,
    { align: 'right', width: 50 }
  );
};

/**
 * Add User Report Content
 */
const addUserReportContent = (doc, data) => {
  if (!data || !data.length) {
    doc.fontSize(12).fillColor(BRAND_COLORS.text).text('No data available');
    return;
  }

  const headers = ['Name', 'Email', 'Department', 'Job Title', 'Status', 'Courses', 'Points'];
  const colWidths = [100, 120, 80, 80, 50, 50, 50];

  addPDFTable(doc, headers, data.map(row => [
    row.fullName || row.name || '-',
    row.email || '-',
    row.department || '-',
    row.jobTitle || '-',
    row.status || '-',
    String(row.coursesCompleted || 0),
    String(row.totalPoints || 0)
  ]), colWidths);
};

/**
 * Add Course Completion Content
 */
const addCourseCompletionContent = (doc, data) => {
  if (!data || !data.length) {
    doc.fontSize(12).fillColor(BRAND_COLORS.text).text('No data available');
    return;
  }

  const headers = ['Course', 'Category', 'Enrollments', 'Completed', 'Rate %', 'Avg Time'];
  const colWidths = [140, 80, 70, 70, 50, 70];

  addPDFTable(doc, headers, data.map(row => [
    row.courseTitle || '-',
    row.category || '-',
    String(row.totalEnrollments || 0),
    String(row.completedCount || 0),
    `${row.completionRate || 0}%`,
    `${row.avgTimeSpentMinutes || 0} min`
  ]), colWidths);
};

/**
 * Add Learning Engagement Content
 */
const addLearningEngagementContent = (doc, data) => {
  if (!data || (Array.isArray(data) && data.length === 0)) {
    doc.fontSize(12).fillColor(BRAND_COLORS.text).text('No data available');
    return;
  }

  // Summary section
  doc.fontSize(14).fillColor(BRAND_COLORS.secondary).text('Summary Statistics');
  doc.moveDown(0.5);

  // Handle array format (converted data from service)
  if (Array.isArray(data)) {
    data.forEach(item => {
      doc.fontSize(11)
         .fillColor(BRAND_COLORS.text)
         .text(`${item.metric}: `, { continued: true })
         .fillColor(BRAND_COLORS.primary)
         .text(String(item.value || 0));
    });
  } else {
    // Handle object format (raw data)
    const stats = [
      ['Total Active Users', data.totalActiveUsers || 0],
      ['Users with Enrollments', data.usersWithEnrollments || 0],
      ['Total Enrollments', data.totalEnrollments || 0],
      ['Total Time Spent', `${data.totalTimeSpentMinutes || 0} minutes`],
      ['Average Time per User', `${data.avgTimePerUser || 0} minutes`],
      ['Active Last Week', data.activeLastWeek || 0]
    ];

    stats.forEach(([label, value]) => {
      doc.fontSize(11)
         .fillColor(BRAND_COLORS.text)
         .text(`${label}: `, { continued: true })
         .fillColor(BRAND_COLORS.primary)
         .text(String(value));
    });
  }
};

/**
 * Add Skills Assessment Content
 */
const addSkillsAssessmentContent = (doc, data) => {
  if (!data || !data.length) {
    doc.fontSize(12).fillColor(BRAND_COLORS.text).text('No data available');
    return;
  }

  const headers = ['Skill', 'Average Score', 'Users Assessed'];
  const colWidths = [200, 150, 150];

  addPDFTable(doc, headers, data.map(row => [
    row.skill || '-',
    `${row.score || 0}%`,
    String(row.usersAssessed || 0)
  ]), colWidths);
};

/**
 * Add generic table content
 */
const addGenericTableContent = (doc, data) => {
  if (!data || !data.length) {
    doc.fontSize(12).fillColor(BRAND_COLORS.text).text('No data available');
    return;
  }

  const headers = Object.keys(data[0]);
  const colWidth = Math.floor(500 / headers.length);
  const colWidths = headers.map(() => colWidth);

  addPDFTable(doc, headers, data.map(row =>
    headers.map(h => String(row[h] || '-'))
  ), colWidths);
};

/**
 * Add table to PDF
 */
const addPDFTable = (doc, headers, rows, colWidths) => {
  const startX = 50;
  let startY = doc.y;
  const rowHeight = 25;
  const pageHeight = doc.page.height - 60;

  // Draw header
  doc.rect(startX, startY, colWidths.reduce((a, b) => a + b, 0), rowHeight)
     .fill(BRAND_COLORS.primary);

  let x = startX;
  headers.forEach((header, i) => {
    doc.fontSize(9)
       .fillColor(BRAND_COLORS.white)
       .text(header, x + 5, startY + 8, { width: colWidths[i] - 10, align: 'left' });
    x += colWidths[i];
  });

  startY += rowHeight;

  // Draw rows
  rows.forEach((row, rowIndex) => {
    // Check if we need a new page
    if (startY + rowHeight > pageHeight) {
      doc.addPage();
      startY = 50;

      // Redraw header on new page
      doc.rect(startX, startY, colWidths.reduce((a, b) => a + b, 0), rowHeight)
         .fill(BRAND_COLORS.primary);

      x = startX;
      headers.forEach((header, i) => {
        doc.fontSize(9)
           .fillColor(BRAND_COLORS.white)
           .text(header, x + 5, startY + 8, { width: colWidths[i] - 10, align: 'left' });
        x += colWidths[i];
      });
      startY += rowHeight;
    }

    // Alternating row colors
    const bgColor = rowIndex % 2 === 0 ? BRAND_COLORS.lightBg : BRAND_COLORS.white;
    doc.rect(startX, startY, colWidths.reduce((a, b) => a + b, 0), rowHeight)
       .fill(bgColor);

    x = startX;
    row.forEach((cell, i) => {
      doc.fontSize(8)
         .fillColor(BRAND_COLORS.text)
         .text(String(cell).substring(0, 25), x + 5, startY + 8, {
           width: colWidths[i] - 10,
           align: 'left'
         });
      x += colWidths[i];
    });

    startY += rowHeight;
  });
};

/**
 * Generate Excel Report with MultipliersKraft branding
 */
const generateExcel = async (reportType, title, data, options = {}) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'MultipliersKraft LMS';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet(title, {
    headerFooter: {
      firstHeader: '&C&B&16MultipliersKraft LMS',
      firstFooter: '&CGenerated by MultipliersKraft LMS | &D'
    }
  });

  // Add title row with branding
  worksheet.mergeCells('A1:H1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = 'MultipliersKraft LMS';
  titleCell.font = { size: 20, bold: true, color: { argb: 'FFF97316' } };
  titleCell.alignment = { horizontal: 'center' };

  // Add report title
  worksheet.mergeCells('A2:H2');
  const reportTitleCell = worksheet.getCell('A2');
  reportTitleCell.value = title;
  reportTitleCell.font = { size: 16, bold: true, color: { argb: 'FF1E293B' } };
  reportTitleCell.alignment = { horizontal: 'center' };

  // Add metadata
  worksheet.mergeCells('A3:H3');
  const metaCell = worksheet.getCell('A3');
  let metaText = `Generated: ${new Date().toLocaleString()}`;
  if (options.dateRange) {
    metaText += ` | Date Range: ${options.dateRange.from} to ${options.dateRange.to}`;
  }
  if (options.department && options.department !== 'all') {
    metaText += ` | Department: ${options.department}`;
  }
  metaCell.value = metaText;
  metaCell.font = { size: 10, italic: true, color: { argb: 'FF64748B' } };
  metaCell.alignment = { horizontal: 'center' };

  // Empty row
  worksheet.addRow([]);

  // Add data based on report type
  if (data && data.length > 0) {
    const headers = getHeadersForReportType(reportType, data);

    // Add header row
    const headerRow = worksheet.addRow(headers.map(h => h.label));
    headerRow.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFF97316' }
      };
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.alignment = { horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Set column widths
    headers.forEach((header, index) => {
      worksheet.getColumn(index + 1).width = header.width || 15;
    });

    // Add data rows
    data.forEach((row, rowIndex) => {
      const dataRow = worksheet.addRow(headers.map(h => row[h.key] || '-'));
      dataRow.eachCell((cell) => {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: rowIndex % 2 === 0 ? 'FFF8FAFC' : 'FFFFFFFF' }
        };
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
        };
      });
    });
  }

  // Save file
  const fileName = generateFileName(reportType, 'xlsx');
  const filePath = path.join(REPORTS_DIR, fileName);
  await workbook.xlsx.writeFile(filePath);

  return {
    fileName,
    filePath,
    format: 'xlsx',
    size: fs.statSync(filePath).size
  };
};

/**
 * Get headers configuration based on report type
 */
const getHeadersForReportType = (reportType, data) => {
  switch (reportType) {
    case 'user':
      return [
        { key: 'fullName', label: 'Full Name', width: 25 },
        { key: 'email', label: 'Email', width: 30 },
        { key: 'department', label: 'Department', width: 15 },
        { key: 'jobTitle', label: 'Job Title', width: 20 },
        { key: 'status', label: 'Status', width: 12 },
        { key: 'joinDate', label: 'Join Date', width: 15 },
        { key: 'coursesCompleted', label: 'Courses Completed', width: 18 },
        { key: 'totalPoints', label: 'Total Points', width: 15 }
      ];
    case 'course-completion':
      return [
        { key: 'courseTitle', label: 'Course Title', width: 35 },
        { key: 'category', label: 'Category', width: 20 },
        { key: 'totalEnrollments', label: 'Total Enrollments', width: 18 },
        { key: 'completedCount', label: 'Completed', width: 15 },
        { key: 'completionRate', label: 'Completion Rate %', width: 18 },
        { key: 'avgTimeSpentMinutes', label: 'Avg Time (min)', width: 15 }
      ];
    case 'learning-engagement':
      return [
        { key: 'metric', label: 'Metric', width: 30 },
        { key: 'value', label: 'Value', width: 20 }
      ];
    default:
      // Auto-generate headers from data keys
      if (data && data.length > 0) {
        return Object.keys(data[0]).map(key => ({
          key,
          label: key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1'),
          width: 15
        }));
      }
      return [];
  }
};

/**
 * Generate CSV Report
 */
const generateCSV = async (reportType, title, data, options = {}) => {
  if (!data || !data.length) {
    throw new Error('No data provided for CSV generation');
  }

  const headers = Object.keys(data[0]);

  // Build CSV content
  let csvContent = '';

  // Add metadata as comments
  csvContent += `# MultipliersKraft LMS - ${title}\n`;
  csvContent += `# Generated: ${new Date().toISOString()}\n`;
  if (options.dateRange) {
    csvContent += `# Date Range: ${options.dateRange.from} to ${options.dateRange.to}\n`;
  }
  if (options.department && options.department !== 'all') {
    csvContent += `# Department: ${options.department}\n`;
  }
  csvContent += '#\n';

  // Add header row
  csvContent += headers.map(h => `"${h}"`).join(',') + '\n';

  // Add data rows
  data.forEach(row => {
    csvContent += headers.map(h => {
      const value = row[h];
      if (value === null || value === undefined) return '""';
      // Escape quotes and wrap in quotes
      return `"${String(value).replace(/"/g, '""')}"`;
    }).join(',') + '\n';
  });

  // Save file
  const fileName = generateFileName(reportType, 'csv');
  const filePath = path.join(REPORTS_DIR, fileName);
  fs.writeFileSync(filePath, csvContent, 'utf8');

  return {
    fileName,
    filePath,
    format: 'csv',
    size: fs.statSync(filePath).size
  };
};

/**
 * Main function to generate report in specified format
 */
const generateReport = async (reportType, format, title, data, options = {}) => {
  switch (format.toLowerCase()) {
    case 'pdf':
      return generatePDF(reportType, title, data, options);
    case 'excel':
    case 'xlsx':
      return generateExcel(reportType, title, data, options);
    case 'csv':
      return generateCSV(reportType, title, data, options);
    default:
      throw new Error(`Unsupported format: ${format}`);
  }
};

/**
 * Delete old report files (cleanup)
 */
const cleanupOldReports = async (maxAgeHours = 24) => {
  const files = fs.readdirSync(REPORTS_DIR);
  const now = Date.now();
  const maxAge = maxAgeHours * 60 * 60 * 1000;

  files.forEach(file => {
    const filePath = path.join(REPORTS_DIR, file);
    const stats = fs.statSync(filePath);
    if (now - stats.mtimeMs > maxAge) {
      fs.unlinkSync(filePath);
    }
  });
};

module.exports = {
  generateReport,
  generatePDF,
  generateExcel,
  generateCSV,
  cleanupOldReports,
  REPORTS_DIR
};
